
package proyecto_aula_2.pkg0;

import javax.swing.JOptionPane;

/**
 *
 * @author YARITZA
 */
public class Inicio_seccion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio_seccion.class.getName());
    private funciones a;
    /**
     * Creates new form NewJFrame
     */
    public Inicio_seccion(funciones funcion) {
        this.a = funcion;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImajenCostado_inicio = new javax.swing.JLabel();
        ImajenFondo_Inicio = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tx_pass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tx_usuario = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tx_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio-seccion-icono-usuario.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 70, -1));

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Iniciar seccion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, 28));

        tx_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_passActionPerformed(evt);
            }
        });
        jPanel1.add(tx_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 151, -1));

        jLabel3.setText("contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        tx_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_usuarioActionPerformed(evt);
            }
        });
        jPanel1.add(tx_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 151, -1));

        jToggleButton1.setText("continuar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 120, -1));

        jLabel2.setText("usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 51, -1));

        jButton1.setText("Registrarse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));
        jPanel1.add(tx_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 170, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_usuarioActionPerformed
       
    }//GEN-LAST:event_tx_usuarioActionPerformed

    private void tx_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_passActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      new registro (this.a).setVisible(true);
                    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
 String email = tx_usuario.getText();
 String contrasena = tx_pass.getText();

    if(email.isEmpty() || contrasena.isEmpty()){
        JOptionPane.showMessageDialog(null, "Digite algo en usuario y en contraseña");
        
    }

    if(email.equalsIgnoreCase("heibran@gmail.com") && contrasena.equals("123456")){
        new bienvenido().setVisible(true);
        this.dispose();
        
    }
    
    boolean encontrado = false;
    System.out.print("hola");
    for(int p = 0; p <= a.cantvendedor; p++){
          
        if (a.usuarios[p] != null ) {
        System.out.print("\n Antes del condicional");  
        System.out.print("\n" + this.a.usuarios[p].getNombreCompleto());  
        System.out.print("\n" + this.a.usuarios[p].getCedula());  }
        
       if (a.usuarios[p].getEmail() != null || a.usuarios[p].getPassword() != null ) {
              System.out.print("Despues del condicional");   
             if(a.usuarios[p].getEmail().equalsIgnoreCase(email) && a.usuarios[p].getPassword().equals(contrasena)){
                if(a.usuarios[p].getrol() == "2"){
                a.IDusuarioactual = p;
                a.cedulausuarioactual = a.usuarios[p].getCedula();
                new Vista_vendedor(a).setVisible(true);
                
                this.dispose();
                encontrado = true;
                break;}  if(a.usuarios[p].getrol() == "1"){
                a.IDusuarioactual = p;
                a.cedulausuarioactual = a.usuarios[p].getCedula();
                new vista_usuario().setVisible(true);
                this.dispose();
                encontrado = true;
                break;}
            
        }
}
           
    }

    if(!encontrado){
         tx_error.setText("Usuario o contraseña incorrectos");
    }
        
                // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
funciones f1 = new funciones();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Inicio_seccion(f1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImajenCostado_inicio;
    private javax.swing.JLabel ImajenFondo_Inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel tx_error;
    private javax.swing.JTextField tx_pass;
    private javax.swing.JTextField tx_usuario;
    // End of variables declaration//GEN-END:variables
}
