/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_aula_2.pkg0;

import java.awt.Color;

/**
 *
 * @author YARITZA
 */
public class registro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(registro.class.getName());
     private funciones a;
    /**
     * Creates new form registro
     */
    public registro(funciones f1) {
        this.a = f1;
        initComponents();
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tx_registronombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tx_registroapellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tx_registroemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tx_registrocontraseña = new javax.swing.JTextField();
        b_terminarR = new javax.swing.JButton();
        tx_registrotipo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        L_registroerror = new javax.swing.JLabel();
        error_email = new javax.swing.JLabel();
        error_tipo = new javax.swing.JLabel();
        error_cedula = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setForeground(new java.awt.Color(0, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 125, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 653, 110));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 66, 28));

        tx_registronombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_registronombreActionPerformed(evt);
            }
        });
        jPanel1.add(tx_registronombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 155, 28));

        jLabel3.setText("Cedula");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 176, 66, 20));
        jPanel1.add(tx_registroapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 155, 31));

        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 216, 66, 20));
        jPanel1.add(tx_registroemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 155, 30));

        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 66, -1));
        jPanel1.add(tx_registrocontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 155, 30));

        b_terminarR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-agregar-usuario.png"))); // NOI18N
        b_terminarR.setText("Registrarse");
        b_terminarR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_terminarRMouseEntered(evt);
            }
        });
        b_terminarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_terminarRActionPerformed(evt);
            }
        });
        jPanel1.add(b_terminarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 150, 40));

        tx_registrotipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_registrotipoActionPerformed(evt);
            }
        });
        jPanel1.add(tx_registrotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 155, 30));

        jLabel6.setText("Dijite el numero de  su occion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        jLabel7.setText("1. Usuario 2.Vendedor");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));
        jPanel1.add(L_registroerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 506, 155, 28));

        error_email.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(error_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 120, 30));

        error_tipo.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(error_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 137, 30));
        jPanel1.add(error_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 180, 31));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_registro.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 106, 660, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_registronombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_registronombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_registronombreActionPerformed

    private void b_terminarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_terminarRActionPerformed
      
      L_registroerror.setText("");
      error_email.setText("");
      error_tipo.setText("");
      error_cedula.setText("");
      String Rnombre = tx_registronombre.getText();
      String Rcedula = tx_registroapellido.getText();
      String Remail = tx_registroemail.getText();
      String Rcontraseña = tx_registrocontraseña.getText();
      String Rtipo = tx_registrotipo.getText();
       boolean Cemail = false;
       boolean verificarvacio = true;
       System.out.print(Rtipo);
       if(Remail.isEmpty() || Rnombre.isEmpty() || Rcedula.isEmpty() || Rcontraseña.isEmpty()|| Rtipo.isEmpty() ){

           L_registroerror.setText("Hay partes en blanco en sus datos");
           verificarvacio = false; 
        }
      if(Remail.contains("@") && Remail.contains(".")){
            Cemail=true;
      }
      
      if( Cemail==false ){
       error_email.setText("Email no valido");
      }
           
     boolean Ctipo = true;
      if(!(Rtipo.equalsIgnoreCase("usuario") || Rtipo.equals("1") || Rtipo.equalsIgnoreCase("vendedor") || Rtipo.equals("2"))){
     
          error_tipo.setText("dijite una de las occiones");
          Ctipo = false;
      }
     boolean unica = true;
      if(a.validarCedula(Rcedula)==false){
         error_cedula.setText("dijite una cedula valida");
          for (int e = 0; e < a.cantusuario; e++) {
              if (Rcedula == a.usuarios[e].cedula) {
                  unica = false;
                  
              }
              
          }
      }
       if ( Cemail == true && verificarvacio == true && a.validarCedula(Rcedula) == true && Ctipo == true && unica == true){
           
            if(Rtipo.equalsIgnoreCase("usuario") || Rtipo.equals("1")){
            
                
                 a.gusuario(Rnombre, Rcedula, Remail, Rcontraseña,"1");
                  new inicio_secion(a).setVisible(true);
                  this.dispose();
            }
            if(Rtipo.equalsIgnoreCase("vendedor") || Rtipo.equals("2")){
                
                a.gusuario(Rnombre, Rcedula, Remail, Rcontraseña,"2");
                 new inicio_secion(a).setVisible(true);
                 this.dispose();
               
            }
      }
           
    }//GEN-LAST:event_b_terminarRActionPerformed

    private void b_terminarRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_terminarRMouseEntered
       b_terminarR.setBackground(new Color(204,0,204));// TODO add your handling code here:
    }//GEN-LAST:event_b_terminarRMouseEntered

    private void tx_registrotipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_registrotipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_registrotipoActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked

        new inicio_secion(a).setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        funciones aA = new funciones();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new registro(aA).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_registroerror;
    private javax.swing.JButton b_terminarR;
    private javax.swing.JLabel error_cedula;
    private javax.swing.JLabel error_email;
    private javax.swing.JLabel error_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tx_registroapellido;
    private javax.swing.JTextField tx_registrocontraseña;
    private javax.swing.JTextField tx_registroemail;
    private javax.swing.JTextField tx_registronombre;
    private javax.swing.JTextField tx_registrotipo;
    // End of variables declaration//GEN-END:variables
}
