/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_aula_2.pkg0;

import java.awt.Color;

/**
 *
 * @author YARITZA
 */
public class registro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(registro.class.getName());
     private funciones a;
    /**
     * Creates new form registro
     */
    public registro(funciones f1) {
        this.a = f1;
        initComponents();
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tx_registronombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tx_registroapellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tx_registroemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tx_registrocontraseña = new javax.swing.JTextField();
        b_terminarR = new javax.swing.JButton();
        tx_registrotipo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        L_registroerror = new javax.swing.JLabel();
        error_email = new javax.swing.JLabel();
        error_tipo = new javax.swing.JLabel();
        error_cedula = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setForeground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 653, -1));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 126, 66, 28));

        tx_registronombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_registronombreActionPerformed(evt);
            }
        });
        jPanel1.add(tx_registronombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 126, 155, 28));

        jLabel3.setText("Cedula");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 173, 66, -1));
        jPanel1.add(tx_registroapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 166, 155, 31));

        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 215, 66, -1));
        jPanel1.add(tx_registroemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 207, 155, 30));

        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 250, 66, -1));
        jPanel1.add(tx_registrocontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 243, 155, 30));

        b_terminarR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-agregar-usuario.png"))); // NOI18N
        b_terminarR.setText("terminar registro");
        b_terminarR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_terminarRMouseEntered(evt);
            }
        });
        b_terminarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_terminarRActionPerformed(evt);
            }
        });
        jPanel1.add(b_terminarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, 36));

        tx_registrotipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_registrotipoActionPerformed(evt);
            }
        });
        jPanel1.add(tx_registrotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 344, 155, 30));

        jLabel6.setText("Dijite el numero de  su occion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 294, -1, -1));

        jLabel7.setText("1. Usuario 2.Vendedor");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 316, -1, -1));
        jPanel1.add(L_registroerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 506, 155, 28));

        error_email.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(error_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 207, 101, 30));

        error_tipo.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(error_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 354, 137, 30));
        jPanel1.add(error_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 166, 101, 31));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-agregar-usuario.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 344, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_registronombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_registronombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_registronombreActionPerformed

    private void b_terminarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_terminarRActionPerformed
      
      L_registroerror.setText("");
      error_email.setText("");
      error_tipo.setText("");
      error_cedula.setText("");
      String Rnombre = tx_registronombre.getText();
      String Rcedula = tx_registroapellido.getText();
      String Remail = tx_registroemail.getText();
      String Rcontraseña = tx_registrocontraseña.getText();
      String Rtipo = tx_registrotipo.getText();
       boolean Cemail = false;
       boolean verificarvacio = true;
       System.out.print(Rtipo);
       if(Remail.isEmpty() || Rnombre.isEmpty() || Rcedula.isEmpty() || Rcontraseña.isEmpty()|| Rtipo.isEmpty() ){

           L_registroerror.setText("Hay partes en blanco en sus datos");
           verificarvacio = false; 
        }
      if(Remail.contains("@") && Remail.contains(".")){
            Cemail=true;
      }
      
      if( Cemail==false ){
       error_email.setText("Email no valido");
      }
           
     boolean Ctipo = true;
      if(!(Rtipo.equalsIgnoreCase("usuario") || Rtipo.equals("1") || Rtipo.equalsIgnoreCase("vendedor") || Rtipo.equals("2"))){
     
          error_tipo.setText("dijite una de las occiones");
          Ctipo = false;
      }

      if(a.validarCedula(Rcedula)==false){
         error_cedula.setText("dijite una cedula valida");
      }
       if ( Cemail == true && verificarvacio == true && a.validarCedula(Rcedula) == true && Ctipo == true){
           
            if(Rtipo.equalsIgnoreCase("usuario") || Rtipo.equals("1")){
            
                
                 a.gusuario(Rnombre, Rcedula, Remail, Rcontraseña,"1");
                  new Inicio_seccion(a).setVisible(true);
                  this.dispose();
            }
            if(Rtipo.equalsIgnoreCase("vendedor") || Rtipo.equals("2")){
                
                a.gusuario(Rnombre, Rcedula, Remail, Rcontraseña,"2");
                 new Inicio_seccion(a).setVisible(true);
                 this.dispose();
               
            }
      }
           
    }//GEN-LAST:event_b_terminarRActionPerformed

    private void b_terminarRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_terminarRMouseEntered
       b_terminarR.setBackground(new Color(204,0,204));// TODO add your handling code here:
    }//GEN-LAST:event_b_terminarRMouseEntered

    private void tx_registrotipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_registrotipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_registrotipoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        funciones aA = new funciones();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new registro(aA).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_registroerror;
    private javax.swing.JButton b_terminarR;
    private javax.swing.JLabel error_cedula;
    private javax.swing.JLabel error_email;
    private javax.swing.JLabel error_tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tx_registroapellido;
    private javax.swing.JTextField tx_registrocontraseña;
    private javax.swing.JTextField tx_registroemail;
    private javax.swing.JTextField tx_registronombre;
    private javax.swing.JTextField tx_registrotipo;
    // End of variables declaration//GEN-END:variables
}
