/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_aula_2.pkg0;

/**
 *
 * @author YARITZA
 */
public class Vista_vendedor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista_vendedor.class.getName());
     private funciones a;
    /**
     * Creates new form Vista_vendedor
     */
    public Vista_vendedor(funciones a ) {
        this.a = new funciones();
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        j_nombre_usuario = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        j_email_vendedor = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        icono_usuario = new javax.swing.JLabel();
        pa_ventas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pa_nueva_venta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        imagen_de_vista_vendedor2 = new javax.swing.JLabel();
        pestanas_vista_vendedor = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        tx_cedula_editar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tx_correo_editar = new javax.swing.JTextField();
        tx_contraseña_editar = new javax.swing.JTextField();
        tx_nombre_editar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        L_error_correo = new javax.swing.JLabel();
        L_error_correo_editar = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        imagen_de_vista_vendedor1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tx_nombre_producto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tx_descripcion_producto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tx_precio_producto = new javax.swing.JTextField();
        b_new_objeto = new javax.swing.JButton();
        error_precio = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        fondo_muestra_datos_vendedor = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        j_cedula_vendedor = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        j_contrasena_vendedor = new javax.swing.JLabel();
        b_modificar_vendedor = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        fondo_new__venta = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jButton1.setText("jButton1");

        j_nombre_usuario.setText("ksjv ");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField5.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        jTextField5.setText("jTextField5");

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icono_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio_usuario.png"))); // NOI18N
        icono_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icono_usuarioMouseClicked(evt);
            }
        });
        jPanel1.add(icono_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 60, 70));

        pa_ventas.setBackground(new java.awt.Color(255, 135, 56));
        pa_ventas.setForeground(new java.awt.Color(255, 102, 0));
        pa_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pa_ventasMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ventas");

        javax.swing.GroupLayout pa_ventasLayout = new javax.swing.GroupLayout(pa_ventas);
        pa_ventas.setLayout(pa_ventasLayout);
        pa_ventasLayout.setHorizontalGroup(
            pa_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pa_ventasLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(66, 66, 66))
        );
        pa_ventasLayout.setVerticalGroup(
            pa_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_ventasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pa_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 170, 30));

        pa_nueva_venta.setBackground(new java.awt.Color(255, 135, 56));
        pa_nueva_venta.setForeground(new java.awt.Color(255, 102, 0));
        pa_nueva_venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pa_nueva_ventaMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nuevo producto");

        javax.swing.GroupLayout pa_nueva_ventaLayout = new javax.swing.GroupLayout(pa_nueva_venta);
        pa_nueva_venta.setLayout(pa_nueva_ventaLayout);
        pa_nueva_ventaLayout.setHorizontalGroup(
            pa_nueva_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_nueva_ventaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pa_nueva_ventaLayout.setVerticalGroup(
            pa_nueva_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_nueva_ventaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pa_nueva_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 170, 30));

        imagen_de_vista_vendedor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main-background.jpg"))); // NOI18N
        imagen_de_vista_vendedor2.setText(" new bienvenido().setVisible(true);");
        jPanel1.add(imagen_de_vista_vendedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 440));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tx_cedula_editar.setEditable(false);
        jPanel3.add(tx_cedula_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 140, -1));

        jLabel12.setText("Nombre");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        jLabel13.setText("Cedula");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        jLabel14.setText("Correo");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        jLabel15.setText("Contraseña");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 20));
        jPanel3.add(tx_correo_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 140, -1));
        jPanel3.add(tx_contraseña_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 140, -1));
        jPanel3.add(tx_nombre_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 140, -1));

        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("Si no desea modificar un parametro dejelo en blanco");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 40));

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 120, -1));

        L_error_correo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_editar.png"))); // NOI18N
        jPanel3.add(L_error_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 240, 260));
        jPanel3.add(L_error_correo_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 70, 20));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pestanas_vista_vendedor.addTab("tab4", jPanel3);

        imagen_de_vista_vendedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono.png"))); // NOI18N
        imagen_de_vista_vendedor1.setText(" new bienvenido().setVisible(true);");
        pestanas_vista_vendedor.addTab("tab5", imagen_de_vista_vendedor1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Dijite el nombre del producto");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));
        jPanel2.add(tx_nombre_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 300, -1));

        jLabel6.setText("Descipcion del objeto");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));
        jPanel2.add(tx_descripcion_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 300, 120));

        jLabel7.setText("Dijite el precio en dolares");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        tx_precio_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tx_precio_productoKeyTyped(evt);
            }
        });
        jPanel2.add(tx_precio_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 200, -1));

        b_new_objeto.setText("Subir producto");
        b_new_objeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_new_objetoActionPerformed(evt);
            }
        });
        jPanel2.add(b_new_objeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        error_precio.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(error_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 120, 20));

        pestanas_vista_vendedor.addTab("tab3", jPanel2);

        jPanel1.add(pestanas_vista_vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 500, 310));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo_muestra_datos_vendedor.setBackground(new java.awt.Color(0, 0, 0));
        fondo_muestra_datos_vendedor.setForeground(new java.awt.Color(0, 0, 0));
        fondo_muestra_datos_vendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_de_muestra_de_datos_vendedor.jpg"))); // NOI18N
        fondo_muestra_datos_vendedor.setText("c");
        jPanel6.add(fondo_muestra_datos_vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, 0, 1050, 380));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nombre :");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cedula :");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));
        jPanel4.add(j_cedula_vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 170, 20));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Email :");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 50, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("contraseña :");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        jPanel4.add(j_contrasena_vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 130, 20));

        b_modificar_vendedor.setText("Modificar algun parametro");
        b_modificar_vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_modificar_vendedorActionPerformed(evt);
            }
        });
        jPanel4.add(b_modificar_vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 180, 30));

        jButton4.setText("Cerrar secion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 500, 275));

        fondo_new__venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_nuevo_objeto.jpg"))); // NOI18N
        jPanel6.add(fondo_new__venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 10, 800, 360));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pa_nueva_ventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pa_nueva_ventaMouseClicked
       
        pestanas_vista_vendedor.setSelectedIndex(2);
        
    }//GEN-LAST:event_pa_nueva_ventaMouseClicked

    private void pa_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pa_ventasMouseClicked
        pestanas_vista_vendedor.setSelectedIndex(1);
    }//GEN-LAST:event_pa_ventasMouseClicked

    private void icono_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icono_usuarioMouseClicked
    j_nombre_usuario.setText(""+a.usuarios[a.IDusuarioactual].getNombreCompleto());
    j_cedula_vendedor.setText(""+a.usuarios[a.IDusuarioactual].getCedula());
    j_email_vendedor.setText(""+a.usuarios[a.IDusuarioactual].getEmail());
    j_contrasena_vendedor.setText(""+a.usuarios[a.IDusuarioactual].getPassword());
        pestanas_vista_vendedor.setSelectedIndex(0);
    }//GEN-LAST:event_icono_usuarioMouseClicked

    private void b_new_objetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_new_objetoActionPerformed
    
        String nombre = tx_nombre_producto.getText();
        String descripcion = tx_descripcion_producto.getText();
        String precioo = tx_precio_producto.getText();
        
        if(!nombre.isEmpty() && !descripcion.isEmpty() && !precioo.isEmpty() ){
            int precio = Integer.parseInt(precioo);
            a.Guardarproducto(nombre, descripcion, precio);
            for(int c = 0;c < 7 ; c ++ )        
            System.out.print(a.productos[c].nombre);
                    
                    
            
    }
        else{}


        // TODO add your handling code here:
    }//GEN-LAST:event_b_new_objetoActionPerformed

    private void tx_precio_productoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_precio_productoKeyTyped
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
        evt.consume();
        error_precio.setText("dijite solo numeros");
        }
    }//GEN-LAST:event_tx_precio_productoKeyTyped

    private void b_modificar_vendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_modificar_vendedorActionPerformed
       
      /*  tx_cedula_editar.setText(""+a.vendedores[a.IDusuarioactual][1]);*/
        
        pestanas_vista_vendedor.setSelectedIndex(3);
    }//GEN-LAST:event_b_modificar_vendedorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       L_error_correo_editar.setText("");
         String nombre = tx_nombre_editar.getText();
        String correo = tx_correo_editar.getText();
        String contraseña = tx_contraseña_editar.getText();
       /* if (!nombre.isEmpty()){
            a.vendedores[a.IDusuarioactual][0] = nombre ;
        } if (correo.isEmpty()){
            if(a.validarcorreo(nombre)){
            a.vendedores[a.IDusuarioactual][2] = correo ;
        }}if (!contraseña.isEmpty()){
            a.vendedores[a.IDusuarioactual][3] = contraseña ;
        }
         if(!a.validarcorreo(nombre)){
            L_error_correo_editar.setText("Correo no valido");
        }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        j_nombre_usuario.setText(""+a.usuarios[a.IDusuarioactual].getNombreCompleto());
    j_cedula_vendedor.setText(""+a.usuarios[a.IDusuarioactual].getCedula());
    j_email_vendedor.setText(""+a.usuarios[a.IDusuarioactual].getEmail());
    j_contrasena_vendedor.setText(""+a.usuarios[a.IDusuarioactual].getPassword());
    pestanas_vista_vendedor.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         new Inicio_seccion(a).setVisible(true);      
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
funciones f2 = new funciones();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Vista_vendedor(f2).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_error_correo;
    private javax.swing.JLabel L_error_correo_editar;
    private javax.swing.JButton b_modificar_vendedor;
    private javax.swing.JButton b_new_objeto;
    private javax.swing.JLabel error_precio;
    private javax.swing.JLabel fondo_muestra_datos_vendedor;
    private javax.swing.JLabel fondo_new__venta;
    private javax.swing.JLabel icono_usuario;
    private javax.swing.JLabel imagen_de_vista_vendedor1;
    private javax.swing.JLabel imagen_de_vista_vendedor2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel j_cedula_vendedor;
    private javax.swing.JLabel j_contrasena_vendedor;
    private javax.swing.JLabel j_email_vendedor;
    private javax.swing.JLabel j_nombre_usuario;
    private javax.swing.JPanel pa_nueva_venta;
    private javax.swing.JPanel pa_ventas;
    private javax.swing.JTabbedPane pestanas_vista_vendedor;
    private javax.swing.JTextField tx_cedula_editar;
    private javax.swing.JTextField tx_contraseña_editar;
    private javax.swing.JTextField tx_correo_editar;
    private javax.swing.JTextField tx_descripcion_producto;
    private javax.swing.JTextField tx_nombre_editar;
    private javax.swing.JTextField tx_nombre_producto;
    private javax.swing.JTextField tx_precio_producto;
    // End of variables declaration//GEN-END:variables
}
